[package]
name = "krwallet"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.45", features = ["derive"]}
csv = "1.3.1"
serde = {version = "1.0.219", features = ["derive"]}

[[bin]]
name = "krwallet"
path = "src/bin/main.rs"
